collection_name: agent
persist_directory: chroma_db
k: 3
# 知识库根目录（建议放侗族织绣相关资料）
data_path: data/dong_embroidery
md5_hex_store: md5.text
allow_knowledge_file_type: [".txt", ".pdf"]

chunk_size: 200
chunk_overlap: 20
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]
